import de.jf.flippingblocks.Enum.EnumColor;
import de.jf.flippingblocks.spielelemente.Block;
import de.jf.flippingblocks.spielelemente.Spalte;
import de.jf.flippingblocks.spielelemente.Spielfeld;

import java.awt.Graphics;
import java.util.ArrayList;

import javax.swing.JLabel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * 
 * @author Jan
 */
public class runner extends javax.swing.JFrame {

	/**
	 * Creates new form runner
	 */
	Spielfeld feld;

	public runner() {
		initComponents();
		feld = new Spielfeld(6, 6);
		zaehler = 0;
	}

	public void zeichnen() {
		Graphics zfeld = jPanel1.getGraphics();
		zfeld.clearRect(0, 0, jPanel1.getWidth(), jPanel1.getHeight());
		int height = jPanel1.getHeight()
				/ feld.getBlocks().get(0).getVisible_length() + 1;
		int i = 0;
		int i2 = 0;
		for (Spalte sp : feld.getBlocks()) {
			for (Block b : sp.getSpalte()) {
				zfeld.setColor(b.getColor2());
				zfeld.fillRect(height * i, jPanel1.getHeight() - (height * i2)
						- height, height, height);
				i2++;
			}
			i++;
			i2 = 0;
		}
		this.setTitle("" + zaehler);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jButton1 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jPanel1MouseClicked(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 0,
				Short.MAX_VALUE));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 326,
				Short.MAX_VALUE));

		jButton1.setText("jButton1");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup().addContainerGap()
								.addComponent(jButton1)
								.addContainerGap(373, Short.MAX_VALUE))
				.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addComponent(jButton1)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										17, Short.MAX_VALUE)
								.addComponent(jPanel1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		feld = new Spielfeld(6, 6);
		zeichnen();
		zaehler = 0;
	}// GEN-LAST:event_jButton1ActionPerformed

	private int zaehler = 0;

	private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jPanel1MouseClicked
		System.out.println(evt.getX() + "/" + evt.getY());
		int height = jPanel1.getHeight()
				/ feld.getBlocks().get(feld.getBlocks().size() - 1)
						.getVisible_length() + 1;
		int x = evt.getX() / height;
		System.out.println(x);
		int y = feld.getBlocks().get(x).getVisible_length() - 1 - evt.getY()
				/ height;
		System.out.println(x + "/" + y);

		ArrayList<Block> e = new ArrayList<>();
		e = feld.CheckMate(e, feld.getBlocks().get(x).getSpalte().get(y), feld
				.getBlocks().get(x).getSpalte().get(y).getColor());
		if (e.size() >= 3) {
			zaehler = zaehler + e.size();
			feld.destroyBlocks(e);

			zeichnen();
		}

	}// GEN-LAST:event_jPanel1MouseClicked

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(runner.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(runner.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(runner.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(runner.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new runner().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JPanel jPanel1;
	// End of variables declaration//GEN-END:variables
}
